-- Execute manually only with approved Snowflake credentials.
CREATE DATABASE IF NOT EXISTS SERVICE_OPS;
CREATE SCHEMA IF NOT EXISTS SERVICE_OPS.RAW;
CREATE SCHEMA IF NOT EXISTS SERVICE_OPS.ANALYTICS;
CREATE WAREHOUSE IF NOT EXISTS SERVICE_OPS_XS
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
CREATE ROLE IF NOT EXISTS SERVICE_OPS_LOADER;
CREATE ROLE IF NOT EXISTS SERVICE_OPS_ANALYST;
GRANT USAGE ON WAREHOUSE SERVICE_OPS_XS TO ROLE SERVICE_OPS_LOADER;
GRANT USAGE ON DATABASE SERVICE_OPS TO ROLE SERVICE_OPS_LOADER;
GRANT USAGE ON SCHEMA SERVICE_OPS.RAW TO ROLE SERVICE_OPS_LOADER;
GRANT CREATE TABLE ON SCHEMA SERVICE_OPS.RAW TO ROLE SERVICE_OPS_LOADER;
GRANT USAGE ON DATABASE SERVICE_OPS TO ROLE SERVICE_OPS_ANALYST;
GRANT USAGE ON SCHEMA SERVICE_OPS.ANALYTICS TO ROLE SERVICE_OPS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SERVICE_OPS.ANALYTICS TO ROLE SERVICE_OPS_ANALYST;
