CREATE FILE FORMAT IF NOT EXISTS SERVICE_OPS.RAW.PARQUET_FORMAT TYPE = PARQUET;
CREATE STAGE IF NOT EXISTS SERVICE_OPS.RAW.LOCAL_PARQUET_STAGE FILE_FORMAT = SERVICE_OPS.RAW.PARQUET_FORMAT;
-- Put files using an approved client, then run COPY manually:
-- COPY INTO SERVICE_OPS.RAW.TICKETS FROM @SERVICE_OPS.RAW.LOCAL_PARQUET_STAGE/tickets.parquet;
CREATE TABLE IF NOT EXISTS SERVICE_OPS.RAW.TICKET_EVENTS (
    payload VARIANT,
    ingested_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE STREAM IF NOT EXISTS SERVICE_OPS.RAW.TICKET_EVENTS_STREAM
    ON TABLE SERVICE_OPS.RAW.TICKET_EVENTS;
-- Example task intentionally starts suspended; resume only after reviewing cost and dependencies.
CREATE TASK IF NOT EXISTS SERVICE_OPS.ANALYTICS.PROCESS_TICKET_EVENTS
    WAREHOUSE = SERVICE_OPS_XS
    SCHEDULE = 'USING CRON 0 * * * * UTC'
    SUSPEND_TASK_AFTER_NUM_FAILURES = 3
AS
INSERT INTO SERVICE_OPS.ANALYTICS.TICKET_EVENTS SELECT * FROM SERVICE_OPS.RAW.TICKET_EVENTS_STREAM;
